### ISSUE TITLE
Test suite throwing connection timeout

### ISSUE THREAD

**Issue by AldanaQuintana** [brandonhilkert/sucker_punch#138]
Hi. Not sure if this is really an issue or if we are doing something wrong. I've searched the internet for help but we are still struggling with this problem...

We are using sucker punch to send emails on background and to process some responses of external services asynchronously. We also wrote some tests, using the configuration suggested on readme.

Everything was working fine until we decided to implement a new actor, that is no different from the others. Now the test suite is throwing "ActiveRecord::ConnectionTimeoutError".

We are using ActiveRecord::Base.connection_pool.with_connection method passing a block to it in almost every actor because most of them interact with database. In addition, we usually handle some business related exceptions inside of that block. Like this:

```
def perform
  ActiveRecord::Base.connection_pool.with_connection do
    begin
      ... # do something
    rescue SomeException => e
      ... # handle exception
    end
  end
end
```

I've posted a [question](http://stackoverflow.com/questions/33613544/sucker-punch-tests-in-rails-using-connection-pool-block-results-in-connection) on stack overflow, and will keep this updated if we find a solution.

Thank you in advance.

**Comment by brandonhilkert** [comment]
Have you tried configuring the ActiveRecord connection pool to be larger?

**Comment by AldanaQuintana** [comment]
No, I haven't. And I realize why this would be a solution. But since I don't understand the underlying problem I don't know if this would be just like hiding it.

**Comment by brandonhilkert** [comment]
The problem seems to be obtaining a connection. Spawning a good amount of
threads that interact with the DB will use up connections. I don't know the
specifics of how many you have setup and the number of jobs in the system,
but it sounds related to your current database adapter settings.


------------------------------------
*Build a Ruby Gem is available!
<http://brandonhilkert.com/books/build-a-ruby-gem/?utm_source=gmail-sig&utm_medium=email&utm_campaign=gmail>*

http://brandonhilkert.com
