### ISSUE TITLE
Problens on heroku

### ISSUE THREAD

**Issue by nonato** [brandonhilkert/sucker_punch#140]
Hello, good morning.

I am using a gem "sucker_punch" in my application, which executes a delayed task a few hours after an object is saved in the database.

This task works fine on my development machine. But when put into production heroku, it does not.

Is there any extra configuration I need to do on heroku?

Already, thank you very much.

**Comment by brandonhilkert** [comment]
Heroku restarts your processes each day. In doing so, any scheduled job would be lost because they're stored in memory. 

Because of this, you might considering adding a database record for the task with the intended execution time, and then using the Heroku scheduler addon to run the tasks where execution times are in the past.

**Comment by nonato** [comment]
Thanks!
