### ISSUE TITLE
sucker_punch seems to have problems with Phusion Passenger

### ISSUE THREAD

**Issue by gduprey** [brandonhilkert/sucker_punch#6]
I got sucker_punch working in just a few minutes in my development environment.  However, when attempting to deploy into a production environment using Phusion Passenger, I'm seeing problems.  

One is that while there are no errors displayed, any attempt to queue a worker/task async doesn't do anything.  The call completes, but the worker never seems to run.

The other, which may inform this, is that attempts to query the state of a queue after submitting a task yield a fatal (deadlock detected) error

Specifically, in code that looks like this:

```
SuckerPunch::Queue[:history_queue].async.perform(Admin::User.current_user.id, new_fav)
puts " ** QUEUED History for SuckerPunch, SIZE=[#{SuckerPunch::Queue[:history_queue].size.to_s}], BUSY=[#{SuckerPunch::Queue[:history_queue].busy_size.to_s}]"
```

Th line with the puts, trying to query the queue causes the above deadlock to occur. And, per the former note, even though the '....async.perform(xxx)' call doesnt pass an error, the actual worker for this never runs (or at least the perform() method isn't called).

Under development (using the standard 'rails server' webrick server), all works without an error.

Is there anything special about setting up sucker_punch to make it work with tools like passenger?

**Comment by richww** [comment]
Hi folks,

I'm still running into this issue on Passenger 5.0.21 / Ruby 2.2.2 / Rails 4.2.5 / sucker_punch 1.6.0, even though according to this section of the README the issue should now be resolved: 

> Previously, Sucker Punch required an initializer and that posed problems for Unicorn and Passenger and other servers that fork. Version 1 was rewritten to not require any special code to be executed after forking occurs. Please remove if you're using version >= 1.0.0

I have an issue where a SuckerPunch Job is not executing asynchronously. On Webrick, it works fine, but on Passenger nothing happens.

I confirmed that my Passenger is using "Smart spawning" and therefore forking, and I also verified that forcing "Direct spawning" in Apache's httpd.conf, the Job works as expected.

So, I had to add this block to an initializer to ensure the Celluloid worker pool was running on the forked Passenger processes:

    if defined?(PhusionPassenger)
      PhusionPassenger.on_event(:starting_worker_process) do |forked|
        if forked
          pool_class = [My::Suckerpunch::Job::Class]
          pool_name = "sucker_punch_[my_suckerpunch_job_class]"
          pool = Class.new(Celluloid::Supervision::Container) do
               pool pool_class, as: pool_name, size: num_workers
          end
          pool.run!
        end
      end
    end
 
Regarding why I need to run the pool for each forked process, I think I see where the problem is. See queue.rb here:

    def registered?
      Celluloid::Actor.registered.include?(name.to_sym)
    end

This is returning true within the forked Passenger thread, so Celluloid is representing the actor as registered for our Job. However, the worker pool isn't running to actually execute the job.

So, am I missing something? What was done to fix this issue within sucker_punch 1.0? Or perhaps a recent update to sucker-punch or celluloid has brought this problem back?

Thanks for any help or insight you could provide.

**Comment by brandonhilkert** [comment]
@richww Can you give the latest `2.0.0` beta a shot? I'm not inclined to go back and dig in to that version at this point.

**Comment by richww** [comment]
@brandonhilkert Yup, 2.0.0 seems to fix the Passenger smart spawning issue for me, thanks!

**Comment by brandonhilkert** [comment]
Great news! Thanks for the feedback!

On Tuesday, January 26, 2016, richww <notifications@github.com> wrote:

> @brandonhilkert <https://github.com/brandonhilkert> Yup, 2.0.0 seems to
> fix the Passenger smart spawning issue for me, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brandonhilkert/sucker_punch/issues/6#issuecomment-175223450>
> .
>


-- 

------------------------------------
*Build a Ruby Gem is available!
<http://brandonhilkert.com/books/build-a-ruby-gem/?utm_source=gmail-sig&utm_medium=email&utm_campaign=gmail>*

http://brandonhilkert.com
