### ISSUE TITLE
Can multiple workers share a queue?

### ISSUE THREAD

**Issue by gduprey** [brandonhilkert/sucker_punch#7]
Pardon the question (vs issue)

From what I can see, it looks like every worker is going to have to have it's own queue.  I'll eventually have about 14 distinct workers, but really do not need 14 queues.  In fact, I'd get by with a default queue and a low-priority queue.  

Can queues be shared by workers or is the queue to worker ratio always 1:1?

Thanks!

**Comment by waiting-for-dev** [comment]
Hey, I was looking for the same.

I have been load testing my application and I have found out that, if I quickly launch 5 different jobs, database connections are exhausted.

First, I was surprised because I'm using `ActiveRecord::Base.connection_pool.with_connection` stuff, but then I realized what it is happening. Each of the 5 jobs belong to different job classes, so each one has its own queue. So, even if each queue size is 2, in fact I'm firing up 5 threads. As all of this is happening fast, when the 6th request comes in none of the 5 previous jobs are finished, so there is no more database connections available (connection pool is 5).

Then, my question is whether the reason why Sucker Punch can't share queues between job classes is inherent the way it works (keeping queues in memory), or it is just to keep things simple.

I guess that as everything happens in the same process there is no way to ensure a global queue size. At most, we could force a global queue per process, but it wouldn't be totally useful for all scenarios. For instance,  in my scenario, if I scale up another process then suddenly the number of database connections at the same time allowed by Sucker Punch would have doubled. When scaling one up, I should remember to divide maximum process global queue size by 2. I recognize that it is quite dirty.

So, I would like to have confirmation about if I'm right with the reasons why there is no global queue in Sucker Punch. If I'm not, that would be very useful :)

Thanks for this great gem!

**Comment by brandonhilkert** [comment]
There's no global queue because it wasn't part of my use case when I was building it. I suppose it could happen with some work, but honestly this is where using something like Sidekiq is probably more appropriate. 

With multi-threaded systems, DB connections are something we need to consider. I often have pools of hundreds in my larger Sidekiq systems.
